import request from "supertest";
import mongoose from "mongoose";

import app from "../src/app.js";

import User from "../src/models/User.js";
import Slot from "../src/models/Slot.js";
import Booking from "../src/models/Booking.js";

import bcrypt from "bcrypt";

import { createAccessToken } from "../src/utils/jwt.js";

describe("Booking Concurrency", () => {
  let counsellor;
  let slot;
  let students;

  beforeEach(async () => {
    /*
     * Clean only the records created by
     * this concurrency test.
     */

    await Booking.deleteMany({
      slotId: {
        $exists: true,
      },
    });

    await Slot.deleteMany({
      startAt: {
        $gte: new Date(),
      },
    });

    await User.deleteMany({
      email: {
        $regex: /^concurrency-/,
      },
    });

    /*
     * Create counsellor.
     */

    counsellor = await User.create({
      name: "Concurrency Counsellor",
      email: `concurrency-counsellor-${Date.now()}@test.local`,
      passwordHash: await bcrypt.hash(
        "TestPassword123!",
        10
      ),
      role: "counsellor",
      isActive: true,
    });

    /*
     * Create slot with capacity = 5.
     *
     * Start time is safely more than
     * 30 minutes in the future.
     */

    const startAt = new Date(
      Date.now() +
        2 * 60 * 60 * 1000
    );

    const endAt = new Date(
      startAt.getTime() +
        30 * 60 * 1000
    );

    slot = await Slot.create({
      counsellorId:
        counsellor._id,

      startAt,

      endAt,

      capacity: 5,

      bookedCount: 0,

      status: "open",
    });

    /*
     * Create 40 different students.
     */

    const passwordHash =
      await bcrypt.hash(
        "TestPassword123!",
        10
      );

    students = await User.insertMany(
      Array.from(
        {
          length: 40,
        },
        (_, index) => ({
          name:
            `Concurrency Student ${index + 1}`,

          email:
            `concurrency-${Date.now()}-${index}@test.local`,

          passwordHash,

          role: "student",

          isActive: true,
        })
      )
    );
  });

  afterEach(async () => {
    /*
     * Remove bookings generated by
     * this test.
     */

    if (slot?._id) {
      await Booking.deleteMany({
        slotId: slot._id,
      });

      await Slot.deleteOne({
        _id: slot._id,
      });
    }

    if (students?.length) {
      await User.deleteMany({
        _id: {
          $in: students.map(
            (student) =>
              student._id
          ),
        },
      });
    }

    if (counsellor?._id) {
      await User.deleteOne({
        _id: counsellor._id,
      });
    }
  });

  test(
    "allows exactly capacity bookings under 40 concurrent requests",
    async () => {
      /*
       * Generate access tokens for all
       * 40 students.
       */

      const requests =
        students.map((student) => {
          const token =
            createAccessToken(
              student
            );

          return request(app)
            .post("/api/bookings")
            .set(
              "Authorization",
              `Bearer ${token}`
            )
            .send({
              slotId:
                slot._id.toString(),
            });
        });

      /*
       * IMPORTANT:
       *
       * Promise.all starts all 40
       * HTTP requests concurrently.
       */

      const responses =
        await Promise.all(
          requests
        );

      /*
       * Count successful bookings.
       */

      const successful =
        responses.filter(
          (response) =>
            response.status === 201
        );

      /*
       * Count capacity conflicts.
       */

      const conflicts =
        responses.filter(
          (response) =>
            response.status === 409
        );

      /*
       * Exactly 5 students should
       * successfully book.
       */

      expect(
        successful.length
      ).toBe(5);

      /*
       * Remaining 35 requests should
       * receive a conflict.
       */

      expect(
        conflicts.length
      ).toBe(35);

      /*
       * Every response must be either
       * success or conflict.
       */

      expect(
        successful.length +
          conflicts.length
      ).toBe(40);

      /*
       * Verify the actual database
       * state.
       */

      const finalSlot =
        await Slot.findById(
          slot._id
        ).lean();

      expect(
        finalSlot
      ).not.toBeNull();

      /*
       * bookedCount must never exceed
       * capacity.
       */

      expect(
        finalSlot.bookedCount
      ).toBe(5);

      expect(
        finalSlot.bookedCount
      ).toBeLessThanOrEqual(
        finalSlot.capacity
      );

      /*
       * Verify actual booking documents.
       */

      const bookings =
        await Booking.find({
          slotId: slot._id,

          status: "booked",
        }).lean();

      /*
       * Exactly 5 booking documents
       * must exist.
       */

      expect(
        bookings.length
      ).toBe(5);

      /*
       * Verify each successful
       * booking belongs to a different
       * student.
       */

      const studentIds =
        bookings.map(
          (booking) =>
            booking.studentId.toString()
        );

      expect(
        new Set(studentIds).size
      ).toBe(5);
    },
    30000
  );
});