export const ERROR_CODES = Object.freeze({
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_REQUIRED: "AUTH_REQUIRED",

  FORBIDDEN: "FORBIDDEN",

  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_ID: "INVALID_ID",

  SLOT_FULL: "SLOT_FULL",

  DUPLICATE_BOOKING: "DUPLICATE_BOOKING",
  BOOKING_OVERLAP: "BOOKING_OVERLAP",
  BOOKING_WINDOW_CLOSED: "BOOKING_WINDOW_CLOSED",

  CANCELLATION_WINDOW_CLOSED: "CANCELLATION_WINDOW_CLOSED",

  INVALID_BOOKING_TRANSITION: "INVALID_BOOKING_TRANSITION",

  WAITLIST_DUPLICATE: "WAITLIST_DUPLICATE",

  STALE_RESOURCE: "STALE_RESOURCE",

  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
});